// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatProto.proto

package com.dnnt.touch.protobuf;

public final class ChatProto {
  private ChatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dnnt.touch.protobuf.ChatMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 from = 1;</code>
     */
    long getFrom();

    /**
     * <code>int64 to = 2;</code>
     */
    long getTo();

    /**
     * <code>int64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>string msg = 4;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>int32 type = 5;</code>
     */
    int getType();

    /**
     * <code>int32 seq = 6;</code>
     */
    int getSeq();
  }
  /**
   * Protobuf type {@code com.dnnt.touch.protobuf.ChatMsg}
   */
  public  static final class ChatMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dnnt.touch.protobuf.ChatMsg)
      ChatMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMsg() {
      from_ = 0L;
      to_ = 0L;
      time_ = 0L;
      msg_ = "";
      type_ = 0;
      seq_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              from_ = input.readInt64();
              break;
            }
            case 16: {

              to_ = input.readInt64();
              break;
            }
            case 24: {

              time_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 40: {

              type_ = input.readInt32();
              break;
            }
            case 48: {

              seq_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dnnt.touch.protobuf.ChatProto.internal_static_com_dnnt_touch_protobuf_ChatMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dnnt.touch.protobuf.ChatProto.internal_static_com_dnnt_touch_protobuf_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dnnt.touch.protobuf.ChatProto.ChatMsg.class, com.dnnt.touch.protobuf.ChatProto.ChatMsg.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private long from_;
    /**
     * <code>int64 from = 1;</code>
     */
    public long getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private long to_;
    /**
     * <code>int64 to = 2;</code>
     */
    public long getTo() {
      return to_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>int64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 4;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>int32 type = 5;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int SEQ_FIELD_NUMBER = 6;
    private int seq_;
    /**
     * <code>int32 seq = 6;</code>
     */
    public int getSeq() {
      return seq_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != 0L) {
        output.writeInt64(1, from_);
      }
      if (to_ != 0L) {
        output.writeInt64(2, to_);
      }
      if (time_ != 0L) {
        output.writeInt64(3, time_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
      }
      if (type_ != 0) {
        output.writeInt32(5, type_);
      }
      if (seq_ != 0) {
        output.writeInt32(6, seq_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, from_);
      }
      if (to_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, to_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, seq_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dnnt.touch.protobuf.ChatProto.ChatMsg)) {
        return super.equals(obj);
      }
      com.dnnt.touch.protobuf.ChatProto.ChatMsg other = (com.dnnt.touch.protobuf.ChatProto.ChatMsg) obj;

      boolean result = true;
      result = result && (getFrom()
          == other.getFrom());
      result = result && (getTo()
          == other.getTo());
      result = result && (getTime()
          == other.getTime());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (getType()
          == other.getType());
      result = result && (getSeq()
          == other.getSeq());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrom());
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTo());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dnnt.touch.protobuf.ChatProto.ChatMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dnnt.touch.protobuf.ChatMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dnnt.touch.protobuf.ChatMsg)
        com.dnnt.touch.protobuf.ChatProto.ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dnnt.touch.protobuf.ChatProto.internal_static_com_dnnt_touch_protobuf_ChatMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dnnt.touch.protobuf.ChatProto.internal_static_com_dnnt_touch_protobuf_ChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dnnt.touch.protobuf.ChatProto.ChatMsg.class, com.dnnt.touch.protobuf.ChatProto.ChatMsg.Builder.class);
      }

      // Construct using com.dnnt.touch.protobuf.ChatProto.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        from_ = 0L;

        to_ = 0L;

        time_ = 0L;

        msg_ = "";

        type_ = 0;

        seq_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dnnt.touch.protobuf.ChatProto.internal_static_com_dnnt_touch_protobuf_ChatMsg_descriptor;
      }

      public com.dnnt.touch.protobuf.ChatProto.ChatMsg getDefaultInstanceForType() {
        return com.dnnt.touch.protobuf.ChatProto.ChatMsg.getDefaultInstance();
      }

      public com.dnnt.touch.protobuf.ChatProto.ChatMsg build() {
        com.dnnt.touch.protobuf.ChatProto.ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dnnt.touch.protobuf.ChatProto.ChatMsg buildPartial() {
        com.dnnt.touch.protobuf.ChatProto.ChatMsg result = new com.dnnt.touch.protobuf.ChatProto.ChatMsg(this);
        result.from_ = from_;
        result.to_ = to_;
        result.time_ = time_;
        result.msg_ = msg_;
        result.type_ = type_;
        result.seq_ = seq_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dnnt.touch.protobuf.ChatProto.ChatMsg) {
          return mergeFrom((com.dnnt.touch.protobuf.ChatProto.ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dnnt.touch.protobuf.ChatProto.ChatMsg other) {
        if (other == com.dnnt.touch.protobuf.ChatProto.ChatMsg.getDefaultInstance()) return this;
        if (other.getFrom() != 0L) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != 0L) {
          setTo(other.getTo());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getSeq() != 0) {
          setSeq(other.getSeq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dnnt.touch.protobuf.ChatProto.ChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dnnt.touch.protobuf.ChatProto.ChatMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long from_ ;
      /**
       * <code>int64 from = 1;</code>
       */
      public long getFrom() {
        return from_;
      }
      /**
       * <code>int64 from = 1;</code>
       */
      public Builder setFrom(long value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0L;
        onChanged();
        return this;
      }

      private long to_ ;
      /**
       * <code>int64 to = 2;</code>
       */
      public long getTo() {
        return to_;
      }
      /**
       * <code>int64 to = 2;</code>
       */
      public Builder setTo(long value) {
        
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 3;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 4;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 4;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 4;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 4;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 5;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 5;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 5;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int seq_ ;
      /**
       * <code>int32 seq = 6;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>int32 seq = 6;</code>
       */
      public Builder setSeq(int value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seq = 6;</code>
       */
      public Builder clearSeq() {
        
        seq_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dnnt.touch.protobuf.ChatMsg)
    }

    // @@protoc_insertion_point(class_scope:com.dnnt.touch.protobuf.ChatMsg)
    private static final com.dnnt.touch.protobuf.ChatProto.ChatMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dnnt.touch.protobuf.ChatProto.ChatMsg();
    }

    public static com.dnnt.touch.protobuf.ChatProto.ChatMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMsg>
        PARSER = new com.google.protobuf.AbstractParser<ChatMsg>() {
      public ChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMsg> getParserForType() {
      return PARSER;
    }

    public com.dnnt.touch.protobuf.ChatProto.ChatMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dnnt_touch_protobuf_ChatMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dnnt_touch_protobuf_ChatMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ChatProto.proto\022\027com.dnnt.touch.protob" +
      "uf\"Y\n\007ChatMsg\022\014\n\004from\030\001 \001(\003\022\n\n\002to\030\002 \001(\003\022" +
      "\014\n\004time\030\003 \001(\003\022\013\n\003msg\030\004 \001(\t\022\014\n\004type\030\005 \001(\005" +
      "\022\013\n\003seq\030\006 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_dnnt_touch_protobuf_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dnnt_touch_protobuf_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dnnt_touch_protobuf_ChatMsg_descriptor,
        new java.lang.String[] { "From", "To", "Time", "Msg", "Type", "Seq", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
